# Generated by Django 3.2.7 on 2021-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faqs',
                'managed': True,
            },
        ),
    ]
