# Generated by Django 3.2.7 on 2021-10-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('catalog', '0002_alter_code_code_type'),
        ('budget', '0002_budget_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='expenses_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='expenses_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='spent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.code'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='budgets', to='user.user'),
        ),
    ]
