# Generated by Django 3.2.7 on 2021-10-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
