version: '3'

services:
    pfm_api:
        container_name: pfm_api
        build: .
        command: >
            bash -c "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 8000:8000
        env_file:
            - .env
        depends_on:
            - pfm_db
    pfm_db:
        container_name: pfm_db
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: django
            POSTGRES_DB: pfm_db
        ports:
            - '5432:5432'
