version: '3'

services:
    pfm-service:
        container_name: pfm-service
        build: .
        command: "python src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        env_file:
            - .env
        ports:
            - 8000:8000
