version: '3'

services:
    flask-app-db:
        container_name: flask-app-db
        image: postgres:13
        environment:
            - POSTGRES_USER=flask
            - POSTGRES_PASSWORD=pass
        expose:
            - 5432
        ports:
            - "5436:5432"

    flask-app:
        container_name: flask-app
        build: .
        command: >
            sh -c "flask run"        
        volumes:
            - ./src/:/code
        ports:
            - 5000:5000
        environment:
            - SECRET_KEY=super-secret
            - JWT_SECRET_KEY=flask-^8l-slh!h_=fe-24mvqv)7jm)f@+$stvto!!!(oil&vl#*lp12
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
            - FLASK_ENV=development
            - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://flask:pass@localhost:5436/postgres
            - APP_CONFIG_FILE=config.py
        depends_on:
            - flask-app-db
        network_mode: host