version: '3'

services:
    pfm_api:
        container_name: pfm_api
        build: .
        command: gunicorn pfm.wsgi:application -b 0.0.0.0:8000 -w 2 -t 30
        # command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        expose:
            - 8000
        env_file:
            - ec2.env
        depends_on:
            - pfm_db
            - pfm_redis
    pfm_db:
        container_name: pfm_db
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: django
            POSTGRES_DB: pfm_db
        volumes:
            - ../postgres-data:/var/lib/postgresql/data
        expose:
            - 5432
    pfm_redis:
        image: 'redis:alpine'
        command: 'redis-server'
        expose:
            - 6379
    pfm_nginx:
        container_name: 'pfm_nginx'
        build: ./nginx
        ports:
            - '80:80'
        depends_on:
            - pfm_api
