version: '3'

services:
    pfm_api:
        container_name: pfm_api
        build: .
        command: 'python manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        env_file:
            - local.env
        depends_on:
            - pfm_db
            # - pfm_redis
    pfm_db:
        container_name: pfm_db
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: django
            POSTGRES_DB: pfm_db
        expose:
            - 5433
    # pfm_redis:
    #     container_name: 'pfm_redis'
    #     image: 'redis:alpine'
    #     command: redis-server
    #     expose:
    #         - 6379
