version: '3.3'

services:
    pfm_api:
        container_name: pfm_api
        build: .
        command: >
            bash -c "python manage.py migrate
            && python manage.py loaddata user/fixtures/users.yaml
            && python manage.py loaddata account/fixtures/accounts.yaml 
            && python manage.py loaddata catalog/fixtures/codetype.yaml
            && python manage.py loaddata catalog/fixtures/accounts_types.yaml
            && python manage.py loaddata catalog/fixtures/transactions_categories_expenses.yaml
            && python manage.py loaddata catalog/fixtures/transactions_categories_incomes.yaml
            && python manage.py loaddata transaction/fixtures/transactions.yaml
            && python manage.py loaddata budget/fixtures/budgets.yaml
            && python manage.py runserver 0.0.0.0:8000"                
        #command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        env_file:
            - local.env
        depends_on:
            - pfm_db
            - pfm_redis
    pfm_db:
        container_name: pfm_db
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: django
            POSTGRES_DB: pfm_db
        ports:
            - '5433:5432'
    pfm_redis:
        image: "redis:alpine"
        command: redis-server
        expose:
            - 6379