# Generated by Django 4.0 on 2022-05-24 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalog_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'catalogs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('metadata', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('process_name', models.CharField(max_length=100, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.catalog')),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
    ]
