# Generated by Django 4.0 on 2022-05-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catalog_id',
            new_name='catalog',
        ),
    ]
