# Generated by Django 4.0 on 2022-05-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_item_catalog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catalog_id',
            new_name='catalog',
        ),
    ]
