# Generated by Django 4.0 on 2022-05-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='budget_amount',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='category',
            new_name='budget_category',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='status',
            new_name='budget_status',
        ),
    ]
