# Generated by Django 4.0 on 2022-05-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_amount_budget_budget_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_amount',
            new_name='amount',
        ),
    ]
