# Generated by Django 4.0 on 2022-03-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_category_budget_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
