# Generated by Django 4.0 on 2022-03-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budget_status_id_alter_budget_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='user_id',
            new_name='user',
        ),
    ]
