# Generated by Django 4.0 on 2022-03-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_category_id_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.UUIDField(db_index=True, default='cbf5eacb-6b1c-42f4-bdba-5a6f6276e0ac'),
        ),
    ]
