# Generated by Django 4.0 on 2022-05-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budget_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_date',
            field=models.DateTimeField(),
        ),
    ]
