# Generated by Django 4.0.1 on 2022-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_budget_budget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
