# Generated by Django 3.2.7 on 2021-09-24 19:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('catalog', '0002_alter_code_code_type'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='catalog.code'),
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('incomes_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incomes_count', models.SmallIntegerField(default=0)),
                ('expenses_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses_count', models.SmallIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('summary_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monthly_summary', to='user.user')),
            ],
            options={
                'db_table': 'monthly_summaries',
                'managed': True,
            },
        ),
    ]
