# Generated by Django 3.2.7 on 2021-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
