# Generated by Django 3.2.7 on 2021-10-01 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_user'),
        ('catalog', '0002_alter_code_code_type'),
        ('user', '0001_initial'),
        ('transaction', '0003_transaction_user_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='catalog.code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_note',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('incomes_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incomes_count', models.SmallIntegerField(default=0)),
                ('expenses_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses_count', models.SmallIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('summary_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monthly_summary', to='user.user')),
            ],
            options={
                'db_table': 'monthly_summaries',
                'managed': True,
            },
        ),
    ]
