# Generated by Django 3.2.7 on 2021-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20211001_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_note',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
