# Generated by Django 4.0 on 2022-05-23 14:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('account_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('ignore_pfm', models.BooleanField(default=False)),
                ('user_note', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_category', to='catalog.item')),
            ],
            options={
                'db_table': 'transactions',
                'managed': True,
            },
        ),
    ]
