# Generated by Django 4.0 on 2022-03-01 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user', models.UUIDField(db_index=True)),
                ('incomes_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incomes_count', models.SmallIntegerField(default=0)),
                ('expenses_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses_count', models.SmallIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('summary_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'monthly_summaries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('account', models.UUIDField(db_index=True)),
                ('category', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('user_note', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': True,
            },
        ),
    ]
