# Generated by Django 4.0 on 2022-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.UUIDField(db_index=True, default='b9e605ee-4cca-400e-99c5-ae24abca97d5'),
            preserve_default=False,
        ),
    ]
