# Generated by Django 4.0 on 2022-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.UUIDField(db_index=True, default='479ec168013945d0b7042bc4e5d0c4fb'),
            preserve_default=False,
        ),
    ]
