# Generated by Django 4.0 on 2022-03-21 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('note', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'transaction_notes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserClassifiedTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('previous_category_id', models.UUIDField()),
                ('current_category_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'user_classified_transactions',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='MonthlySummary',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_note',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ignore_pfm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userclassifiedtransaction',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='transactionnote',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.transaction'),
        ),
    ]
