# Generated by Django 4.0 on 2022-03-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactionnote_userclassifiedtransaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transactionnote',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='userclassifiedtransaction',
            old_name='current_category_id',
            new_name='current_category',
        ),
        migrations.RenameField(
            model_name='userclassifiedtransaction',
            old_name='previous_category_id',
            new_name='previous_category',
        ),
        migrations.RenameField(
            model_name='userclassifiedtransaction',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
