# Generated by Django 4.0 on 2022-04-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_account_id_transaction_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_note',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
