# Generated by Django 3.2.7 on 2021-10-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_code_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='catalog.codetype'),
        ),
    ]
