name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: w2yg4tCKPgXwKyuB9Db6j0eSgZVzMIWd:621ae9d67e490f18108538c4
